### PR TITLE
shamelessly steal entire implementation from any-promise

### LINKED ISSUE #3: Just use rxjs-minimal instead of both rxjs-full and minimal
See [this comment](https://github.com/sindresorhus/any-observable/commit/33293a53fb7b242aa61c42ea036db5bd849ababf#commitcomment-17275070).

RxJs uses an interesting loader mechanism that allows users to specify exactly which Observable methods are implemented. This allows them to pursue a robust API, and users don't necessarily have to pay the price with larger browserified packages. (I think you can accomplish similar with bluebird, but it requires a build step - rxjs automates feature selection via require/import statements - it's pretty cool). More details [here](http://reactivex.io/rxjs/manual/installation.html)

Anyways. I think we should probably just select the minimal install when auto-resolving. Then users can patch to get the features they want, but we aren't necessarily loading the entirety of rxjs.

### LINKED ISSUE #4: Browser shim
Similar to `any-promise`: https://github.com/kevinbeaty/any-promise/blob/master/register-shim.js

### LINKED ISSUE #6: Should work, even if it's not deduped.
any-promise uses a global to ensure it works, even when it's not deduped.

### LINKED ISSUE #7: Allow for different export patterns.
The string only option does not fit RxJs.

You can't do:

``` js
require('rxjs/Observable');
```

You need to do:

``` js
require('rxjs/Observable').Observable;
```

I think our default lookup strategy should be something like this:

``` js
function load(name) {
  var loaded = require(name);
  return loaded.Observable || loaded.default || loaded;
}
```

### PR DESCRIPTION
**Pull request by jamestalmage**
`any-promise` is just very well thought out, there's no point to reinventing the wheel here.

Adds all the following features:
- `require('any-observable/implementation')` - returns a string containing the implementation name.
- Allows you to register the constructor explicitly.
  
  ``` js
  require('any-observable/register')('my-observable', {Observable: ObservableConstructor});
  ```
- Automatically handles es6 style exports (named or default) - Fixes #7:
  
  ``` js
  var lib = require(implementation);
  var Observable = lib.Observable || lib.default || lib;
  ```
- Creates a global registration, even if `any-observable` is not deduped - Fixes #6
- Global registration can be disabled using `opts.global`
  
  ``` js
  require('any-observable/register')('zen-observable', {global: false});
  ```
- Provides a browser shim - Fixes #4
- Just uses `rxjs/Observable` (minimal) - Fixes #3

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good idea! I naively thought I could do it simpler than `any-promise` initially.

**Comment by sindresorhus** [comment]
> Automatically handles es6 style exports (named or default) 

This is not part of `any-promise`, right? If true, we should document it.

**Comment by jamestalmage** [comment]
> Allows you to register the constructor explicitly.

That's already part of `any-promise`. See the [advanced section](https://github.com/kevinbeaty/any-promise#advanced-registration)

> Automatically handles es6 style exports (named or default)

`any-promise` only does the following:

``` js
var Promise = lib.Promise || lib;
```

we do:

``` js
var Observable = lib.Observable || lib.default || lib;
```

I haven't seen any implementations where that's actually useful yet, just seemed to be sensible - if they export a `default` - use that.

**Comment by sindresorhus** [comment]
Ok, cool.

**Pull request merged**
