### PR TITLE
Support RxJS 6

### LINKED ISSUE #22: Support RxJS 6
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/any-observable/issues/22)

And drop support for RxJS 5.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#23 Support RxJS 6](https://issuehunt.io/r/sindresorhus/any-observable/pull/23)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/any-observable/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by mcmxcdev**
Closes #22.

The PR is in draft state for now, since I didn't have the time yet to test it on an actual project. 
Can I `yarn link` to test it?

I had `rxjs-compat` installed at first to make it a smooth transition and removed it again, so support for RxJS 5 is definitely dropped.

Sorry for all the changes in a single commit, I kind of unexpectedly managed to get it working and passing all the tests right away :)

Looking forward to get some feedback.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#22: Support RxJS 6](https://issuehunt.io/repos/57201062/issues/22)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
I’m not 100% linking will work. You can just copy-paste the directory into your project’s node_modules directory.

**Comment by mcmxcdev** [comment]
@sindresorhus `yarn link` works just fine, fyi ;)
I was able to verify that the implementation works with `zen-observable` as expected through reading the documentation of this repo. 
The other libs I am unsure how to test them correctly. Can you either try this PR out locally yourself or instruct me how to make sure `rxjs-min` etc. still work?

**Comment by sindresorhus** [comment]
> Can you either try this PR out locally yourself or instruct me how to make sure rxjs-min etc. still work?

I honestly don't know. I don't use RxJS.

**Comment by sindresorhus** [comment]
The changes look good to me :)

**Pull request merged**
